TrajectoryPlannerROS:
    max_vel_x: 1.2
    min_vel_x: 0.2
    max_rotational_vel: 2.0
    min_in_place_rotational_vel: 1.0

    acc_lim_th: 3.0
    acc_lim_x: 2.0
    acc_lim_y: 2.0

    holonomic_robot: false
    meter_scoring: true

    vx_samples: 10
    vtheta_samples: 20

    controller_frequency: 10

    yaw_goal_tolerance: 3.14
    xy_goal_tolerance: 0.08
